version: "3.8"
services:
  traefik:
    image: traefik:latest
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80

  python:
    build: ./python/
    volumes:
      - ../src/django:/var/www/html:cached
    ports:
      - 8000:8000
    extra_hosts:
      - host.docker.internal

  node:
    build: ./node/
    volumes:
      - ../src/vue:/var/www/html:cached
    ports:
      - 9000:9000

  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
